gaze_data:
  - path: '/Users/Anton/Downloads/assignment_2_code/inputs/images/pattern0'

iris_data:
  - path: '/Users/Anton/Desktop/data/iris/casia4i.json'

optimization:
  filter_config: bilateral_filter
  strategy: uniform_sampler