data_config: configs/data/home-dev.yaml
filters:
- gaussian_filter
- bilateral_filter
- non_local_means
- gaussian_noise
- uniform_noise
- laplacian_noise
- salt_and_pepper
- snow
- cauchy_noise
- mean_filter
- median_filter
method: NaiveMultiObjectiveOptimizer
metrics:
  gaze_metrics:
  - GazeAccuracy
  iris_metrics:
  - GradientEntropy
  - GaborEntropy
  - ImageSimilarity
  pupil_metrics:
  - PupilDetectionError
metrics_config: configs/metrics/std.yaml
polar_resolution:
- 10
- 100
samples:
  gaze: 50
  iris: 50
  pupil: 50
#strategy_config: configs/strategies/tester.yaml
strategy_config: configs/strategies/27-10-20-linear.yaml
