polar_resolution:
  angular: 100
  radial: 10

constructor_args:
  GradientEntropy:
    histogram_divisions: 16

  GaborEntropy:
    scales: 5
    angles_per_scale: 3
    histogram_divisions: 16

  GazeAccuracy: {}

  PupilDetectionError:
    detectors:
      - ElseDetector

  ImageSimilarity:
    angles: 6
    scales: 4
    eps: 0.0001