gaussian_filter:
  sigma:
    type: samples_num
    params:
      start: 0
      stop: 50
      num: 100


mean_filter:
  size:
    type: samples_step
    params:
      start: 1
      stop: 51
      step: 2


median_filter:
  size:
    type: samples_step
    params:
      start: 1
      stop: 51
      step: 2


bilateral_filter:
  sigma_s:
    type: samples_num
    params:
      start: 1
      stop: 20
      num: 30
  sigma_c:
    type: samples_num
    params:
      start: 5
      stop: 100
      num: 30


super_filter:
  sigma_s:
    type: samples_num
    params:
      start: 1
      stop: 20
      num: 10
  sigma_c:
    type: samples_num
    params:
      start: 10
      stop: 60
      num: 10
  scale:
    type: samples_num
    params:
      start: 1
      stop: 50
      num: 20


super_filter_reverse:
  sigma_s:
    type: samples_num
    params:
      start: 1
      stop: 20
      num: 10
  sigma_c:
    type: samples_num
    params:
      start: 10
      stop: 60
      num: 10
  scale:
    type: samples_num
    params:
      start: 1
      stop: 50
      num: 20


anisotropic_diffusion:
  kappa:
    type: samples_num
    params:
      start: 20
      stop: 80
      num: 30
  gamma:
    type: samples_num
    params:
      start: 0.01
      stop: 0.25
      num: 30
  iterations:
    type: const
    params:
      val: 100


non_local_means:
  h:
    type: samples_num
    params:
      start: 0
      stop: 100
      num: 100


uniform_noise:
  intensity:
    type: samples_num
    params:
      start: 0
      stop: 250
      num: 100


gaussian_noise:
  loc:
    type: const
    params:
      val: 0.0
  scale:
    type: samples_num
    params:
      start: 0
      stop: 100
      num: 100


laplacian_noise:
  scale:
    type: samples_num
    params:
      start: 0
      stop: 100
      num: 100


salt_and_pepper:
  intensity:
    type: samples_num
    params:
      start: 0
      stop: 255
      num: 30
  density:
    type: samples_num
    params:
      start: 0.01
      stop: 0.99
      num: 15


snow:
  density:
    type: samples_num
    params:
      start: 0.01
      stop: 0.99
      num: 100


cauchy_noise:
  scale:
    type: samples_num
    params:
      start: 1
      stop: 50
      num: 100
