dataset: /home/anton/data/eyedata/iris/casia4i.json
filters: {}
parameters:
  angles: 6
  epsilon: 0.001
  resolution:
    angular: 100
    radial: 10
  rotation:
    num: 7
    step_size: 3
  scales: 4
