dataset: /home/anton/data/eyedata/iris/casia4i.json
filters:
  bilateral_filter:
    sigma_c: 83.62068965517241
    sigma_s: 12.137931034482758
    steps: 1.0
  gaussian_filter:
    sigma: 4.545454
  gaussian_noise:
    loc: 0.0
    scale: 79.797979797979
  mean_filter:
    size: 7.0
  non_local_means:
    h: 52.52525252525252
  uniform_noise:
    intensity: 222.2222222222
  cauchy_noise:
    scale: 37.62626262626263
  salt_and_pepper:
    intensity: 92.85714285714286
    density: 0.49999999999999994
parameters:
  angles: 6
  epsilon: 0.0001
  resolution:
    angular: 100
    radial: 10
  rotation:
    num: 7
    step_size: 3
  scales: 4
