dataset: /home/anton/data/eyedata/iris/casia4i.json
filters: # Threshold @ 5.5
  bilateral_filter:
    sigma_c: 96.72413793103446
    sigma_s: 11.482758620689653
  gaussian_noise:
    loc: 0.0
    scale: 96.96969696969698
  gaussian_filter:
    sigma: 50
  mean_filter:
    size: 49
  median_filter:
    size: 45
  non_local_means:
    h: 91.91919191919193
  uniform_noise:
    intensity: 244.94949494949478
  cauchy_noise:
    scale: 50
  laplacian_noise:
    scale: 98.989898989899
  snow:
    density: 0.9405050505050502
  salt_and_pepper:
    intensity: 219.82758620689665
    density: 0.7799999999999999
parameters:
  angles: 6
  epsilon: 0.0001
  resolution:
    angular: 100
    radial: 10
  rotation:
    num: 7
    step_size: 3
  scales: 4
