dataset: /home/anton/data/eyedata/iris/casia4i.json
filters: # Threshold @ 5.5
  super_filter:
    sigma_c: 42.2222222222222
    sigma_s: 11.111111111111112
    scale: 5
parameters:
  angles: 6
  epsilon: 0.0001
  resolution:
    angular: 100
    radial: 10
  rotation:
    num: 7
    step_size: 3
  scales: 4
